

default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: postgres
  password: postgres123
  host: localhost
  port: 5432

development:
  <<: *default
  database: auranotes_development

  
test:
  <<: *default
  database: auranotes_test


#
production:
  <<: *default
  database: auranotes_production
  username: auranotes
  password: <%= ENV["AURANOTES_DATABASE_PASSWORD"] %>
